server:
  port: 8088

spring:
  application:
    name: HOTEL-SERVICE
  config:
    import: configserver:http://localhost:8085



#  datasource:
#    url: jdbc:mysql://localhost:3306/microservicesUser
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect