server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservicesUser
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: HOTEL-SERVICE


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect