server:
  port: 8085

spring:
  application:
    name: CONFIG-SERVER

  profiles:
    active: local

  cloud:
    config:
      server:
        git:
          uri: https://github.com/RupaliGuleria/microservice-config-gatewayimpl
         # username: { $USERNAME }
         # password: {$password }
          clone-on-start: true


